// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwngyvatnoeyoaplwoba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3bmd5dmF0bm9leW9hcGx3b2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTUwMTksImV4cCI6MjA1ODc3MTAxOX0.FMYhid7NKwj0IGoHT5y3Iwrte4BIkOzP2xmpyr78Nbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);